[project]
name = "amd-llama-public"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch==2.4.1",
    "transformers>=4.46.3",
]
